services:
  - type: web
    name: discord-keyword-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --schedule
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: OBSIDIAN_VAULT_PATH
        value: /tmp/obsidian
      - key: KEYWORDS
        value: なう,わず,うぃる
      - key: SCHEDULE_TIME
        value: 09:00
